/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.client.master.persistence.entity;

import co.edu.uniandes.csw.co.fantasticos.friend.persistence.entity.FriendEntity;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.entity.ClientEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ClientfacebookFriendsEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ClientfacebookFriendsEntity.getByMasterId", query = "SELECT  u FROM ClientfacebookFriendsEntity u WHERE u.clientId=:clientId"),
    @NamedQuery(name = "ClientfacebookFriendsEntity.deleteClientfacebookFriendsEntity", query = "DELETE FROM ClientfacebookFriendsEntity u WHERE u.clientId=:clientId and  u.facebookFriendsId=:facebookFriendsId"),
    @NamedQuery(name = "ClientfacebookFriendsEntity.deleteAllClientfacebookFriendsEntity", query = "DELETE FROM ClientfacebookFriendsEntity u WHERE u.clientId=:clientId")
})
public class ClientfacebookFriendsEntity implements Serializable {

    @Id
    @Column(name = "clientId")
    private String clientId;
    @Id
    @Column(name = "facebookFriendsId")
    private String facebookFriendsId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "clientId", referencedColumnName = "id")
    @JoinFetch
    private ClientEntity clientIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "facebookFriendsId", referencedColumnName = "id")
    @JoinFetch
    private FriendEntity facebookFriendsIdEntity; 

    public ClientfacebookFriendsEntity() {
    }

    public ClientfacebookFriendsEntity(String clientId, String facebookFriendsId) {
        this.clientId =clientId;
        this.facebookFriendsId = facebookFriendsId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getFacebookFriendsId() {
        return facebookFriendsId;
    }

    public void setFacebookFriendsId(String facebookFriendsId) {
        this.facebookFriendsId = facebookFriendsId;
    }

    public ClientEntity getClientIdEntity() {
        return clientIdEntity;
    }

    public void setClientIdEntity(ClientEntity clientIdEntity) {
        this.clientIdEntity = clientIdEntity;
    }

    public FriendEntity getFacebookFriendsIdEntity() {
        return facebookFriendsIdEntity;
    }

    public void setFacebookFriendsIdEntity(FriendEntity facebookFriendsIdEntity) {
        this.facebookFriendsIdEntity = facebookFriendsIdEntity;
    }

}
