/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.co.fantasticos.client.master.persistence.entity;

import co.edu.uniandes.csw.co.fantasticos.giftcard.persistence.entity.GiftCardEntity;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.entity.ClientEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ClientpurchasedGiftCardsEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ClientpurchasedGiftCardsEntity.getByMasterId", query = "SELECT  u FROM ClientpurchasedGiftCardsEntity u WHERE u.clientId=:clientId"),
    @NamedQuery(name = "ClientpurchasedGiftCardsEntity.deleteClientpurchasedGiftCardsEntity", query = "DELETE FROM ClientpurchasedGiftCardsEntity u WHERE u.clientId=:clientId and  u.purchasedGiftCardsId=:purchasedGiftCardsId")
})
public class ClientpurchasedGiftCardsEntity implements Serializable {

    @Id
    @Column(name = "clientId")
    private String clientId;
    @Id
    @Column(name = "purchasedGiftCardsId")
    private Long purchasedGiftCardsId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "clientId", referencedColumnName = "id")
    @JoinFetch
    private GiftCardEntity clientIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "purchasedGiftCardsId", referencedColumnName = "id")
    @JoinFetch
    private GiftCardEntity purchasedGiftCardsIdEntity; 

    public ClientpurchasedGiftCardsEntity() {
    }

    public ClientpurchasedGiftCardsEntity(String clientId, Long purchasedGiftCardsId) {
        this.clientId =clientId;
        this.purchasedGiftCardsId = purchasedGiftCardsId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public Long getPurchasedGiftCardsId() {
        return purchasedGiftCardsId;
    }

    public void setPurchasedGiftCardsId(Long purchasedGiftCardsId) {
        this.purchasedGiftCardsId = purchasedGiftCardsId;
    }

    public GiftCardEntity getClientIdEntity() {
        return clientIdEntity;
    }

    public void setClientIdEntity(GiftCardEntity clientIdEntity) {
        this.clientIdEntity = clientIdEntity;
    }

    public GiftCardEntity getPurchasedGiftCardsIdEntity() {
        return purchasedGiftCardsIdEntity;
    }

    public void setPurchasedGiftCardsIdEntity(GiftCardEntity purchasedGiftCardsIdEntity) {
        this.purchasedGiftCardsIdEntity = purchasedGiftCardsIdEntity;
    }

}
