/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.client.master.persistence.entity;

import co.edu.uniandes.csw.co.fantasticos.friend.persistence.entity.FriendEntity;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.entity.ClientEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ClientgoogleFriendsEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ClientgoogleFriendsEntity.getByMasterId", query = "SELECT  u FROM ClientgoogleFriendsEntity u WHERE u.clientId=:clientId"),
    @NamedQuery(name = "ClientgoogleFriendsEntity.deleteClientgoogleFriendsEntity", query = "DELETE FROM ClientgoogleFriendsEntity u WHERE u.clientId=:clientId and  u.googleFriendsId=:googleFriendsId"),
    @NamedQuery(name = "ClientgoogleFriendsEntity.deleteAllClientgoogleFriendsEntity", query = "DELETE FROM ClientgoogleFriendsEntity u WHERE u.clientId=:clientId")
})
public class ClientgoogleFriendsEntity implements Serializable {

    @Id
    @Column(name = "clientId")
    private String clientId;
    @Id
    @Column(name = "googleFriendsId")
    private String googleFriendsId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "clientId", referencedColumnName = "id")
    @JoinFetch
    private FriendEntity clientIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "googleFriendsId", referencedColumnName = "id")
    @JoinFetch
    private FriendEntity googleFriendsIdEntity; 

    public ClientgoogleFriendsEntity() {
    }

    public ClientgoogleFriendsEntity(String clientId, String googleFriendsId) {
        this.clientId =clientId;
        this.googleFriendsId = googleFriendsId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getGoogleFriendsId() {
        return googleFriendsId;
    }

    public void setGoogleFriendsId(String googleFriendsId) {
        this.googleFriendsId = googleFriendsId;
    }

    public FriendEntity getClientIdEntity() {
        return clientIdEntity;
    }

    public void setClientIdEntity(FriendEntity clientIdEntity) {
        this.clientIdEntity = clientIdEntity;
    }

    public FriendEntity getGoogleFriendsIdEntity() {
        return googleFriendsIdEntity;
    }

    public void setGoogleFriendsIdEntity(FriendEntity googleFriendsIdEntity) {
        this.googleFriendsIdEntity = googleFriendsIdEntity;
    }

}
