/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.friend.master.logic.ejb;

import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.shop.persistence.api.IShopPersistence;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.shop.persistence.api.IShopPersistence;
import co.edu.uniandes.csw.co.fantasticos.friend.logic.dto.FriendDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.logic.api._IFriendMasterLogicService;
import co.edu.uniandes.csw.co.fantasticos.friend.master.logic.dto.FriendMasterDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.api.IFriendMasterPersistence;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.entity.FriendfacebookLikesEntity;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.entity.FriendgoogleLikesEntity;
import co.edu.uniandes.csw.co.fantasticos.friend.persistence.api.IFriendPersistence;
import javax.inject.Inject;

public abstract class _FriendMasterLogicService implements _IFriendMasterLogicService {

    @Inject
    protected IFriendPersistence friendPersistance;
    @Inject
    protected IFriendMasterPersistence friendMasterPersistance;
    @Inject
    protected IShopPersistence shopPersistance;

    public FriendMasterDTO createMasterFriend(FriendMasterDTO friend) {
        FriendDTO persistedFriendDTO = friendPersistance.createFriend(friend.getFriendEntity());
        if (friend.getCreatefacebookLikes() != null) {
            for (ShopDTO shopDTO : friend.getCreatefacebookLikes()) {
                ShopDTO createdShopDTO = shopPersistance.createShop(shopDTO);
                FriendfacebookLikesEntity friendShopEntity = new FriendfacebookLikesEntity(persistedFriendDTO.getId(), createdShopDTO.getId());
                friendMasterPersistance.createFriendfacebookLikesEntity(friendShopEntity);
            }
        }
        if (friend.getCreategoogleLikes() != null) {
            for (ShopDTO shopDTO : friend.getCreategoogleLikes()) {
                ShopDTO createdShopDTO = shopPersistance.createShop(shopDTO);
                FriendgoogleLikesEntity friendShopEntity = new FriendgoogleLikesEntity(persistedFriendDTO.getId(), createdShopDTO.getId());
                friendMasterPersistance.createFriendgoogleLikesEntity(friendShopEntity);
            }
        }
        // update shop
        if (friend.getUpdatefacebookLikes() != null) {
            for (ShopDTO shopDTO : friend.getUpdatefacebookLikes()) {
                //shopPersistance.updateShop(shopDTO);
                FriendfacebookLikesEntity friendShopEntity = new FriendfacebookLikesEntity(persistedFriendDTO.getId(), shopDTO.getId());
                friendMasterPersistance.createFriendfacebookLikesEntity(friendShopEntity);
            }
        }
        // update shop
        if (friend.getUpdategoogleLikes() != null) {
            for (ShopDTO shopDTO : friend.getUpdategoogleLikes()) {
                //shopPersistance.updateShop(shopDTO);
                FriendgoogleLikesEntity friendShopEntity = new FriendgoogleLikesEntity(persistedFriendDTO.getId(), shopDTO.getId());
                friendMasterPersistance.createFriendgoogleLikesEntity(friendShopEntity);
            }
        }
        return friend;
    }

    public FriendMasterDTO getMasterFriend(String id) {
        return friendMasterPersistance.getFriend(id);
    }

    public void deleteMasterFriend(String id) {
        friendPersistance.deleteFriend(id);
    }

    public void updateMasterFriend(FriendMasterDTO friend) {
        //friendPersistance.updateFriend(friend.getFriendEntity());

        //---- FOR RELATIONSHIP
        // delete shop
        if (friend.getDeletefacebookLikes() != null) {
            for (ShopDTO shopDTO : friend.getDeletefacebookLikes()) {
                friendMasterPersistance.deleteFriendfacebookLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
            }
        }
        // persist new shop
        if (friend.getCreatefacebookLikes() != null) {
            for (ShopDTO shopDTO : friend.getCreatefacebookLikes()) {
                FriendfacebookLikesEntity friendShopEntity = new FriendfacebookLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                friendMasterPersistance.createFriendfacebookLikesEntity(friendShopEntity);
            }
        }
        // update shop
        if (friend.getUpdatefacebookLikes() != null) {
            
            friendMasterPersistance.deleteAllFacebookLikesFromFriend(friend.getFriendEntity().getId());
            
            for (ShopDTO shopDTO : friend.getUpdatefacebookLikes()) {
                //friendMasterPersistance.deleteFriendfacebookLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                //shopPersistance.updateShop(shopDTO);
                FriendfacebookLikesEntity friendShopEntity = new FriendfacebookLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                friendMasterPersistance.createFriendfacebookLikesEntity(friendShopEntity);
                
            }
        }
        // delete shop
        if (friend.getDeletegoogleLikes() != null) {
            for (ShopDTO shopDTO : friend.getDeletegoogleLikes()) {
                friendMasterPersistance.deleteFriendgoogleLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
            }
        }
        // persist new shop
        if (friend.getCreategoogleLikes() != null) {
            for (ShopDTO shopDTO : friend.getCreategoogleLikes()) {
                FriendgoogleLikesEntity friendShopEntity = new FriendgoogleLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                friendMasterPersistance.createFriendgoogleLikesEntity(friendShopEntity);
            }
        }
        // update shop
        if (friend.getUpdategoogleLikes() != null) {
            
            friendMasterPersistance.deleteAllGoogleLikesFromFriend(friend.getFriendEntity().getId());
        
            for (ShopDTO shopDTO : friend.getUpdategoogleLikes()) {
                //friendMasterPersistance.deleteFriendgoogleLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                //shopPersistance.updateShop(shopDTO);
                FriendgoogleLikesEntity friendShopEntity = new FriendgoogleLikesEntity(friend.getFriendEntity().getId(), shopDTO.getId());
                friendMasterPersistance.createFriendgoogleLikesEntity(friendShopEntity);
                
            }
        }
    }
}
