/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.co.fantasticos.giftcard.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.co.fantasticos.giftcard.logic.dto.GiftCardDTO;
import co.edu.uniandes.csw.co.fantasticos.giftcard.persistence.entity.GiftCardEntity;

public abstract class _GiftCardConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static GiftCardDTO entity2PersistenceDTO(GiftCardEntity entity){
		if (entity != null) {
			GiftCardDTO dto = new GiftCardDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setValue(entity.getValue());
 
			    if(entity.getDateCreated() != null){
					dto.setDateCreated(DATE_FORMAT.format(entity.getDateCreated()));
				}	
					dto.setShopId(entity.getShopId());
					dto.setDestinaryId(entity.getDestinaryId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static GiftCardEntity persistenceDTO2Entity(GiftCardDTO dto){
		if(dto!=null){
			GiftCardEntity entity=new GiftCardEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setValue(dto.getValue());
			
 
			      try{ 
			        if(dto.getDateCreated() != null){
						entity.setDateCreated(DATE_FORMAT.parse(dto.getDateCreated()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_GiftCardConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setShopId(dto.getShopId());
			
					entity.setDestinaryId(dto.getDestinaryId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<GiftCardDTO> entity2PersistenceDTOList(List<GiftCardEntity> entities){
		List<GiftCardDTO> dtos=new ArrayList<GiftCardDTO>();
		for(GiftCardEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<GiftCardEntity> persistenceDTO2EntityList(List<GiftCardDTO> dtos){
		List<GiftCardEntity> entities=new ArrayList<GiftCardEntity>();
		for(GiftCardDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}