/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.co.fantasticos.client.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.co.fantasticos.client.logic.dto.ClientDTO;
import co.edu.uniandes.csw.co.fantasticos.client.logic.api.IClientLogicService;
import co.edu.uniandes.csw.co.fantasticos.client.master.logic.api._IClientMasterLogicService;
import co.edu.uniandes.csw.co.fantasticos.client.master.logic.dto.ClientMasterDTO;
import co.edu.uniandes.csw.co.fantasticos.giftcard.logic.api.IGiftCardLogicService;
import co.edu.uniandes.csw.co.fantasticos.giftcard.logic.dto.GiftCardDTO;
import javax.inject.Inject;


public abstract class _ClientMasterMockLogicService implements _IClientMasterLogicService {

    protected static ArrayList<ClientMasterDTO> clientMasterDtosList = new ArrayList<ClientMasterDTO>() ;
    @Inject
    protected IGiftCardLogicService giftCardPersistance;
    @Inject
    protected IClientLogicService clientPersistance;

    public ClientMasterDTO createMasterClient(ClientMasterDTO client) {

        clientPersistance.createClient(client.getClientEntity());
        for (GiftCardDTO dto : client.getCreatepurchasedGiftCards()) {
            giftCardPersistance.createGiftCard(dto);
        }
        clientMasterDtosList.add(client);
        return client;
    }

    public ClientMasterDTO getMasterClient(Long id) {
        for (ClientMasterDTO clientMasterDTO : clientMasterDtosList) {
            if (clientMasterDTO.getClientEntity().getId() == id) {
                return clientMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterClient(Long id) {
        for (ClientMasterDTO clientMasterDTO : clientMasterDtosList) {
            if (clientMasterDTO.getClientEntity().getId() == id) {

                for (GiftCardDTO dto : clientMasterDTO.getCreatepurchasedGiftCards()) {
                    giftCardPersistance.deleteGiftCard(dto.getId());
                }
                clientPersistance.deleteClient(clientMasterDTO.getId());
                clientMasterDtosList.remove(clientMasterDTO);
            }
        }

    }

    public void updateMasterClient(ClientMasterDTO client) {

        // update GiftCard
        if (client.getUpdatepurchasedGiftCards() != null) {
            for (GiftCardDTO dto : client.getUpdatepurchasedGiftCards()) {
                giftCardPersistance.updateGiftCard(dto);
            }
        }
        // persist new GiftCard
        if (client.getCreatepurchasedGiftCards() != null) {
            for (GiftCardDTO dto : client.getCreatepurchasedGiftCards()) {
                GiftCardDTO persistedGiftCardDTO = giftCardPersistance.createGiftCard(dto);
                dto = persistedGiftCardDTO;
            }
        }
        // delete GiftCard
        if (client.getDeletepurchasedGiftCards() != null) {
            for (GiftCardDTO dto : client.getDeletepurchasedGiftCards()) {

                giftCardPersistance.deleteGiftCard(dto.getId());
            }
        }
    }
}