/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.co.fantasticos.client.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.co.fantasticos.client.logic.dto.ClientDTO;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.entity.ClientEntity;

public abstract class _ClientConverter {

	public static ClientDTO entity2PersistenceDTO(ClientEntity entity){
		if (entity != null) {
			ClientDTO dto = new ClientDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setEmail(entity.getEmail());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ClientEntity persistenceDTO2Entity(ClientDTO dto){
		if(dto!=null){
			ClientEntity entity=new ClientEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setEmail(dto.getEmail());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ClientDTO> entity2PersistenceDTOList(List<ClientEntity> entities){
		List<ClientDTO> dtos=new ArrayList<ClientDTO>();
		for(ClientEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ClientEntity> persistenceDTO2EntityList(List<ClientDTO> dtos){
		List<ClientEntity> entities=new ArrayList<ClientEntity>();
		for(ClientDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}