/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.friend.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.co.fantasticos.friend.logic.dto.FriendDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.logic.api.IFriendLogicService;
import co.edu.uniandes.csw.co.fantasticos.friend.master.logic.api._IFriendMasterLogicService;
import co.edu.uniandes.csw.co.fantasticos.friend.master.logic.dto.FriendMasterDTO;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.api.IShopLogicService;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import javax.inject.Inject;


public abstract class _FriendMasterMockLogicService implements _IFriendMasterLogicService {

    protected static ArrayList<FriendMasterDTO> friendMasterDtosList = new ArrayList<FriendMasterDTO>() ;
    @Inject
    protected IShopLogicService shopPersistance;
    @Inject
    protected IFriendLogicService friendPersistance;

    public FriendMasterDTO createMasterFriend(FriendMasterDTO friend) {

        friendPersistance.createFriend(friend.getFriendEntity());
        for (ShopDTO dto : friend.getCreatefacebookLikes()) {
            friend.getListfacebookLikes().add(shopPersistance.createShop(dto));
        }
        for (ShopDTO dto : friend.getCreategoogleLikes()) {
            friend.getListgoogleLikes().add(shopPersistance.createShop(dto));
        }
        friendMasterDtosList.add(friend);
        return friend;
    }

    public FriendMasterDTO getMasterFriend(String id) {
        for (FriendMasterDTO friendMasterDTO : friendMasterDtosList) {
            if (friendMasterDTO.getFriendEntity().getId() == id) {
                return friendMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterFriend(String id) {
        for (FriendMasterDTO friendMasterDTO : friendMasterDtosList) {
            if (friendMasterDTO.getFriendEntity().getId() == id) {

                for (ShopDTO dto : friendMasterDTO.getCreatefacebookLikes()) {
                    shopPersistance.deleteShop(dto.getId());
                }
                friendPersistance.deleteFriend(friendMasterDTO.getId());
                friendMasterDtosList.remove(friendMasterDTO);
                for (ShopDTO dto : friendMasterDTO.getCreategoogleLikes()) {
                    shopPersistance.deleteShop(dto.getId());
                }
                friendPersistance.deleteFriend(friendMasterDTO.getId());
                friendMasterDtosList.remove(friendMasterDTO);
            }
        }

    }

    public void updateMasterFriend(FriendMasterDTO friend) {

		FriendMasterDTO currentFriend = getMasterFriend(friend.getFriendEntity().getId());
		if (currentFriend == null) {
			currentFriend = friend;
		}else{
			friendMasterDtosList.remove(currentFriend);
		}

        // update Shop
        if (friend.getUpdatefacebookLikes() != null) {
            for (ShopDTO dto : friend.getUpdatefacebookLikes()) {
                shopPersistance.updateShop(dto);
                for (ShopDTO shopdto : currentFriend.getListfacebookLikes()) {
					if (shopdto.getId() == dto.getId()) {
						currentFriend.getListfacebookLikes().remove(shopdto);
						currentFriend.getListfacebookLikes().add(dto);
					}
				}
            }
        }
        // persist new Shop
        if (friend.getCreatefacebookLikes() != null) {
            for (ShopDTO dto : friend.getCreatefacebookLikes()) {
                ShopDTO persistedShopDTO = shopPersistance.createShop(dto);
                dto = persistedShopDTO;
                currentFriend.getListfacebookLikes().add(dto);
            }
        }
        // delete Shop
        if (friend.getDeletefacebookLikes() != null) {
            for (ShopDTO dto : friend.getDeletefacebookLikes()) {
				for (ShopDTO shopdto : currentFriend.getListfacebookLikes()) {
					if (shopdto.getId() == dto.getId()) {
						currentFriend.getListfacebookLikes().remove(shopdto);
					}
				}
                shopPersistance.deleteShop(dto.getId());
            }
        }
        // update Shop
        if (friend.getUpdategoogleLikes() != null) {
            for (ShopDTO dto : friend.getUpdategoogleLikes()) {
                shopPersistance.updateShop(dto);
                for (ShopDTO shopdto : currentFriend.getListgoogleLikes()) {
					if (shopdto.getId() == dto.getId()) {
						currentFriend.getListgoogleLikes().remove(shopdto);
						currentFriend.getListgoogleLikes().add(dto);
					}
				}
            }
        }
        // persist new Shop
        if (friend.getCreategoogleLikes() != null) {
            for (ShopDTO dto : friend.getCreategoogleLikes()) {
                ShopDTO persistedShopDTO = shopPersistance.createShop(dto);
                dto = persistedShopDTO;
                currentFriend.getListgoogleLikes().add(dto);
            }
        }
        // delete Shop
        if (friend.getDeletegoogleLikes() != null) {
            for (ShopDTO dto : friend.getDeletegoogleLikes()) {
				for (ShopDTO shopdto : currentFriend.getListgoogleLikes()) {
					if (shopdto.getId() == dto.getId()) {
						currentFriend.getListgoogleLikes().remove(shopdto);
					}
				}
                shopPersistance.deleteShop(dto.getId());
            }
        }
        friendMasterDtosList.add(currentFriend);
    }
}