/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201408112050*/

package co.edu.uniandes.csw.co.fantasticos.client.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.co.fantasticos.client.logic.dto.ClientDTO;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.api._IClientPersistence;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.converter.ClientConverter;
import co.edu.uniandes.csw.co.fantasticos.client.persistence.entity.ClientEntity;

public abstract class _ClientPersistence implements _IClientPersistence {

  	@PersistenceContext(unitName="tuMejorOpcionPU")
 
	protected EntityManager entityManager;
	
	public ClientDTO createClient(ClientDTO client) {
		ClientEntity entity=ClientConverter.persistenceDTO2Entity(client);
		entityManager.persist(entity);
		return ClientConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<ClientDTO> getClients() {
		Query q = entityManager.createQuery("select u from ClientEntity u");
		return ClientConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public ClientDTO getClient(Long id) {
		return ClientConverter.entity2PersistenceDTO(entityManager.find(ClientEntity.class, id));
	}

	public void deleteClient(Long id) {
		ClientEntity entity=entityManager.find(ClientEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateClient(ClientDTO detail) {
		ClientEntity entity=entityManager.merge(ClientConverter.persistenceDTO2Entity(detail));
		ClientConverter.entity2PersistenceDTO(entity);
	}

}