/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.friend.master.logic.dto;

import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.logic.dto.FriendDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _FriendMasterDTO {

 
    protected FriendDTO friendEntity;
    protected String id;
    
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public FriendDTO getFriendEntity() {
        return friendEntity;
    }

    public void setFriendEntity(FriendDTO friendEntity) {
        this.friendEntity = friendEntity;
    }
    
    public List<ShopDTO> createfacebookLikes;
    public List<ShopDTO> updatefacebookLikes;
    public List<ShopDTO> deletefacebookLikes;
    public List<ShopDTO> listfacebookLikes;	
    public List<ShopDTO> creategoogleLikes;
    public List<ShopDTO> updategoogleLikes;
    public List<ShopDTO> deletegoogleLikes;
    public List<ShopDTO> listgoogleLikes;	
	
	
	
    public List<ShopDTO> getCreatefacebookLikes(){ return createfacebookLikes; };
    public void setCreatefacebookLikes(List<ShopDTO> createfacebookLikes){ this.createfacebookLikes=createfacebookLikes; };
    public List<ShopDTO> getUpdatefacebookLikes(){ return updatefacebookLikes; };
    public void setUpdatefacebookLikes(List<ShopDTO> updatefacebookLikes){ this.updatefacebookLikes=updatefacebookLikes; };
    public List<ShopDTO> getDeletefacebookLikes(){ return deletefacebookLikes; };
    public void setDeletefacebookLikes(List<ShopDTO> deletefacebookLikes){ this.deletefacebookLikes=deletefacebookLikes; };
    public List<ShopDTO> getListfacebookLikes(){ return listfacebookLikes; };
    public void setListfacebookLikes(List<ShopDTO> listfacebookLikes){ this.listfacebookLikes=listfacebookLikes; };	
    public List<ShopDTO> getCreategoogleLikes(){ return creategoogleLikes; };
    public void setCreategoogleLikes(List<ShopDTO> creategoogleLikes){ this.creategoogleLikes=creategoogleLikes; };
    public List<ShopDTO> getUpdategoogleLikes(){ return updategoogleLikes; };
    public void setUpdategoogleLikes(List<ShopDTO> updategoogleLikes){ this.updategoogleLikes=updategoogleLikes; };
    public List<ShopDTO> getDeletegoogleLikes(){ return deletegoogleLikes; };
    public void setDeletegoogleLikes(List<ShopDTO> deletegoogleLikes){ this.deletegoogleLikes=deletegoogleLikes; };
    public List<ShopDTO> getListgoogleLikes(){ return listgoogleLikes; };
    public void setListgoogleLikes(List<ShopDTO> listgoogleLikes){ this.listgoogleLikes=listgoogleLikes; };	
	
	
}

