/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.entity;

import co.edu.uniandes.csw.co.fantasticos.shop.persistence.entity.ShopEntity;
import co.edu.uniandes.csw.co.fantasticos.friend.persistence.entity.FriendEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(FriendgoogleLikesEntityId.class)
@NamedQueries({
    @NamedQuery(name = "FriendgoogleLikesEntity.getByMasterId", query = "SELECT  u FROM FriendgoogleLikesEntity u WHERE u.friendId=:friendId"),
    @NamedQuery(name = "FriendgoogleLikesEntity.deleteFriendgoogleLikesEntity", query = "DELETE FROM FriendgoogleLikesEntity u WHERE u.friendId=:friendId and  u.googleLikesId=:googleLikesId"),
    @NamedQuery(name = "FriendgoogleLikesEntity.deleteAllFriendgoogleLikesEntity", query = "DELETE FROM FriendgoogleLikesEntity u WHERE u.friendId=:friendId")
})
public class FriendgoogleLikesEntity implements Serializable {

    @Id
    @Column(name = "friendId")
    private String friendId;
    @Id
    @Column(name = "googleLikesId")
    private String googleLikesId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "friendId", referencedColumnName = "id")
    @JoinFetch
    private FriendEntity friendIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "googleLikesId", referencedColumnName = "id")
    @JoinFetch
    private ShopEntity googleLikesIdEntity; 

    public FriendgoogleLikesEntity() {
    }

    public FriendgoogleLikesEntity(String friendId, String googleLikesId) {
        this.friendId =friendId;
        this.googleLikesId = googleLikesId;
    }

    public String getFriendId() {
        return friendId;
    }

    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    public String getGoogleLikesId() {
        return googleLikesId;
    }

    public void setGoogleLikesId(String googleLikesId) {
        this.googleLikesId = googleLikesId;
    }

    public FriendEntity getFriendIdEntity() {
        return friendIdEntity;
    }

    public void setFriendIdEntity(FriendEntity friendIdEntity) {
        this.friendIdEntity = friendIdEntity;
    }

    public ShopEntity getGoogleLikesIdEntity() {
        return googleLikesIdEntity;
    }

    public void setGoogleLikesIdEntity(ShopEntity googleLikesIdEntity) {
        this.googleLikesIdEntity = googleLikesIdEntity;
    }

}
