/* ========================================================================
   * Copyright 2014 co.fantasticos
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 co.fantasticos
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.co.fantasticos.friend.master.persistence;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.entity.FriendfacebookLikesEntity;
import co.edu.uniandes.csw.co.fantasticos.shop.persistence.converter.ShopConverter;
import co.edu.uniandes.csw.co.fantasticos.shop.logic.dto.ShopDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.entity.FriendgoogleLikesEntity;
import co.edu.uniandes.csw.co.fantasticos.shop.persistence.converter.ShopConverter;
import co.edu.uniandes.csw.co.fantasticos.friend.logic.dto.FriendDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.logic.dto.FriendMasterDTO;
import co.edu.uniandes.csw.co.fantasticos.friend.master.persistence.api._IFriendMasterPersistence;
import co.edu.uniandes.csw.co.fantasticos.friend.persistence.api.IFriendPersistence;
import co.edu.uniandes.csw.co.fantasticos.shop.persistence.api.IShopPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _FriendMasterPersistence implements _IFriendMasterPersistence {

  	@PersistenceContext(unitName="tuMejorOpcionPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IFriendPersistence friendPersistence;
    @Inject
    protected IShopPersistence shopPersistence;

    public FriendMasterDTO getFriend(String friendId) {
        FriendMasterDTO friendMasterDTO = new FriendMasterDTO();
        FriendDTO friend = friendPersistence.getFriend(friendId);
        friendMasterDTO.setFriendEntity(friend);
        friendMasterDTO.setListfacebookLikes(getFriendfacebookLikesEntityList(friendId));
        friendMasterDTO.setListgoogleLikes(getFriendgoogleLikesEntityList(friendId));
        return friendMasterDTO;
    }

    public FriendfacebookLikesEntity createFriendfacebookLikesEntity(FriendfacebookLikesEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteFriendfacebookLikesEntity(String friendId, String facebookLikesId) {
        Query q = entityManager.createNamedQuery("FriendfacebookLikesEntity.deleteFriendfacebookLikesEntity");
        q.setParameter("friendId", friendId);
        q.setParameter("facebookLikesId", facebookLikesId);
        q.executeUpdate();
    }

    public List<ShopDTO> getFriendfacebookLikesEntityList(String friendId) {
        ArrayList<ShopDTO> resp = new ArrayList<ShopDTO>();
        Query q = entityManager.createNamedQuery("FriendfacebookLikesEntity.getByMasterId");
        q.setParameter("friendId",friendId);
        List<FriendfacebookLikesEntity> qResult =  q.getResultList();
        for (FriendfacebookLikesEntity entity : qResult) { 
            
            ShopDTO shopFromMongo = shopPersistence.getShop(entity.getFacebookLikesId());
            resp.add(shopFromMongo);
            
        }
        return resp;
    }
    public FriendgoogleLikesEntity createFriendgoogleLikesEntity(FriendgoogleLikesEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteFriendgoogleLikesEntity(String friendId, String googleLikesId) {
        Query q = entityManager.createNamedQuery("FriendgoogleLikesEntity.deleteFriendgoogleLikesEntity");
        q.setParameter("friendId", friendId);
        q.setParameter("googleLikesId", googleLikesId);
        q.executeUpdate();
    }

    public List<ShopDTO> getFriendgoogleLikesEntityList(String friendId) {
        ArrayList<ShopDTO> resp = new ArrayList<ShopDTO>();
        Query q = entityManager.createNamedQuery("FriendgoogleLikesEntity.getByMasterId");
        q.setParameter("friendId",friendId);
        List<FriendgoogleLikesEntity> qResult =  q.getResultList();
        for (FriendgoogleLikesEntity entity : qResult) { 
            
            ShopDTO shopFromMongo = shopPersistence.getShop(entity.getGoogleLikesId());
            resp.add(shopFromMongo);
            
        }
        return resp;
    }

}
